locals {
  os = data.external.os.result.os
  check = local.os == "Windows" ? "Windows" : "Linux"

  # pfSense builders
  build_pfsense_windows = "..\\..\\bin\\packer.exe build -var vsphere_esxi_host=${var.vsphere_esxi_host} -var vsphere_server=${var.vsphere_server} -var vsphere_username=${var.vsphere_username} -var vsphere_password=${var.vsphere_password} -var vsphere_datastore=${var.vsphere_datastore} -var vsphere_iso_folder=${var.vsphere_iso_folder} -var pfsense_iso_filename=${var.pfsense_iso_filename} -var ssh_username=ansible -var ssh_password=ansible -var http_file_host=${var.http_file_host} -var tailscale_preauth_key=${var.tailscale_preauth_key} -force ..\\..\\packer\\pfsense\\pfsense.pkr.hcl"
  build_pfsense_linux = "packer build -var vsphere_esxi_host=${var.vsphere_esxi_host} -var vsphere_server=${var.vsphere_server} -var vsphere_username=${var.vsphere_username} -var vsphere_password=${var.vsphere_password} -var vsphere_datastore=${var.vsphere_datastore} -var vsphere_iso_folder=${var.vsphere_iso_folder} -var pfsense_iso_filename=${var.pfsense_iso_filename} -var ssh_username=ansible -var ssh_password=ansible -var http_file_host=${var.http_file_host} -var tailscale_preauth_key=${var.tailscale_preauth_key} -force ../../packer/pfsense/pfsense.pkr.hcl"

  # Ubuntu builders
  build_ubuntu_windows = "..\\..\\bin\\packer.exe build -var vsphere_esxi_host=${var.vsphere_esxi_host} -var vsphere_server=${var.vsphere_server} -var vsphere_username=${var.vsphere_username} -var vsphere_password=${var.vsphere_password} -var vsphere_datastore=${var.vsphere_datastore} -var vsphere_iso_folder=${var.vsphere_iso_folder} -var ubuntu_iso_filename=${var.ubuntu_iso_filename} -var ssh_username=ansible -var ssh_password=ansible -var http_file_host=${var.http_file_host} -force ../../packer/ubuntu/ubuntu.pkr.hcl"
  build_ubuntu_linux = "packer build -var vsphere_esxi_host=${var.vsphere_esxi_host} -var vsphere_server=${var.vsphere_server} -var vsphere_username=${var.vsphere_username} -var vsphere_password=${var.vsphere_password} -var vsphere_datastore=${var.vsphere_datastore} -var vsphere_iso_folder=${var.vsphere_iso_folder} -var ubuntu_iso_filename=${var.ubuntu_iso_filename} -var ssh_username=ansible -var ssh_password=ansible -var http_file_host=${var.http_file_host} -force ../../packer/ubuntu/ubuntu.pkr.hcl"


  # Windows 2019 builders
  build_windows2019_windows = "..\\..\\bin\\packer.exe build -var vsphere_esxi_host=${var.vsphere_esxi_host} -var vsphere_server=${var.vsphere_server} -var vsphere_username=${var.vsphere_username} -var vsphere_password=${var.vsphere_password} -var vsphere_datastore=${var.vsphere_datastore} -var vsphere_iso_folder=${var.vsphere_iso_folder} -var server2019_iso_filename=${var.server2019_iso_filename} -force ..\\..\\packer\\windows2019\\windows2019.pkr.hcl"
  build_windows2019_linux = "packer build -var vsphere_esxi_host=${var.vsphere_esxi_host} -var vsphere_server=${var.vsphere_server} -var vsphere_username=${var.vsphere_username} -var vsphere_password=${var.vsphere_password} -var vsphere_datastore=${var.vsphere_datastore} -var vsphere_iso_folder=${var.vsphere_iso_folder} -var server2019_iso_filename=${var.server2019_iso_filename} -force ../../packer/windows2019/windows-2019.pkr.hcl"

  # Windows 2016 builders
  build_windows2016_windows = "..\\..\\bin\\packer.exe build -var vsphere_esxi_host=${var.vsphere_esxi_host} -var vsphere_server=${var.vsphere_server} -var vsphere_username=${var.vsphere_username} -var vsphere_password=${var.vsphere_password} -var vsphere_datastore=${var.vsphere_datastore} -var vsphere_iso_folder=${var.vsphere_iso_folder} -var server2016_iso_filename=${var.server2016_iso_filename} -force ..\\..\\packer\\windows2016\\windows2016.pkr.hcl"
  build_windows2016_linux = "packer build -var vsphere_esxi_host=${var.vsphere_esxi_host} -var vsphere_server=${var.vsphere_server} -var vsphere_username=${var.vsphere_username} -var vsphere_password=${var.vsphere_password} -var vsphere_datastore=${var.vsphere_datastore} -var vsphere_iso_folder=${var.vsphere_iso_folder} -var server2016_iso_filename=${var.server2016_iso_filename} -force ../../packer/windows2016/windows2016.pkr.hcl"
}